const $=id=>document.getElementById(id);const fmt=x=>x==null||x===''?'—':typeof x==='number'?x.toLocaleString('en-IN',{maximumFractionDigits:2}):x;const pct=x=>x==null?'—':fmt(x)+'%';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const HOLIDAYS=new Set(['2026-01-26','2026-03-03','2026-03-26','2026-03-31','2026-04-03','2026-04-14','2026-05-01','2026-05-28','2026-06-26','2026-09-14','2026-10-02','2026-10-20','2026-11-10','2026-11-24','2026-12-25']);
function row(label,value,cls=''){return `<div class="row"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong></div>`}
function currentIST(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date());const o={};parts.forEach(p=>o[p.type]=p.value);return o}
function sessionState(){const p=currentIST(),key=`${p.year}-${p.month}-${p.day}`,mins=Number(p.hour)*60+Number(p.minute);const weekday=new Date(`${key}T00:00:00+05:30`).getUTCDay();return {open:weekday>=1&&weekday<=5&&!HOLIDAYS.has(key)&&mins>=555&&mins<=940,key,time:`${p.hour}:${p.minute}:${p.second}`}}
async function load(){
 $('refreshState').textContent='REFRESHING';
 try{
  const [a,b,c,l]=await Promise.all([fetch('data/market_snapshot.json?x='+Date.now(),{cache:'no-store'}),fetch('data/history.json?x='+Date.now(),{cache:'no-store'}),fetch('data/trade_journal.json?x='+Date.now(),{cache:'no-store'}),fetch('data/learning_state.json?x='+Date.now(),{cache:'no-store'})]);
  if(!a.ok)throw Error('snapshot unavailable');const d=await a.json(),hist=b.ok?await b.json():[],j=c.ok?await c.json():{},learn=l.ok?await l.json():{};const live=sessionState();const m=d.market||{},n=m.NIFTY||{};const opt=d.option_data||{},cand=d.candidate||{},plan=d.plan||{},stats=j.stats||d.journal_stats||{},closed=j.closed||[];
  $('spot').textContent=fmt(d.nifty);$('vix').textContent=fmt(d.vix);$('regime').textContent=d.regime||'—';$('score').textContent=fmt(d.model_score);$('marketTime').textContent=live.time;$('session').textContent=live.open?'MARKET OPEN':'MARKET CLOSED';
  const dec=live.open?(d.decision||'NO TRADE'):'MARKET CLOSED';$('decision').textContent=dec;$('decision').className=dec==='MARKET CLOSED'?'closed':dec==='NO TRADE'?'abstain':'trade';$('reason').textContent=live.open?(d.reason||'—'):'The decision engine is intentionally inactive outside NSE regular derivatives hours (09:15–15:40 IST). Previous decisions remain available only as audit information.';$('strength').textContent=live.open?((d.signal_strength??0)+'/100'):'—';$('optionGate').textContent=live.open?(opt.status||'UNKNOWN'):'SESSION CLOSED';$('validation').textContent=live.open?(d.validation?.hit_rate!=null?d.validation.hit_rate+'%':'NOT AVAILABLE'):'—';$('openPnl').textContent=j.open?.unrealized_pct!=null?pct(j.open.unrealized_pct):'NO OPEN TRADE';$('lastPnl').textContent=closed.length?pct(closed[closed.length-1].realized_pct):'NO CLOSED TRADE';
  $('contract').textContent=live.open?(cand.contractSymbol||'NO VERIFIED CONTRACT'):'SESSION CLOSED';$('entry').textContent=live.open&&plan.entry!=null?'₹'+fmt(plan.entry):'—';$('stop').textContent=live.open&&plan.stop!=null?'₹'+fmt(plan.stop):'—';$('targets').textContent=live.open&&plan.target1!=null?'₹'+fmt(plan.target1)+' / ₹'+fmt(plan.target2):'—';$('planNote').textContent=live.open?(plan.note|| (opt.status==='BLOCKED_NO_RELIABLE_FREE_CHAIN'?'OPTION INTELLIGENCE BLOCKED: no reliable free option chain. The engine will not invent a CALL/PUT.':'No setup has passed every trade gate.')):'No trading signal is generated while the market is closed.';
  $('trend').textContent=n.price?`${fmt(n.price)} | EMA20 ${fmt(n.ema20)} | EMA50 ${fmt(n.ema50)}`:'UNAVAILABLE';$('rsi').textContent=fmt(n.rsi14);$('vwap').textContent=`${fmt(n.vwap)} | ATR ${fmt(n.atr14)}`;$('momentum').textContent=`5m ${pct(n.momentum5m_pct)} | 15m ${pct(n.momentum15m_pct)}`;$('pcr').textContent=`PCR ${fmt(opt.pcr)} | Max pain ${fmt(opt.max_pain)}`;$('optQuality').textContent=live.open?(cand.candidate_score!=null?`${fmt(cand.candidate_score)}/100 | spread ${pct(cand.spread_pct)}`:opt.status||'NOT VERIFIED'):'SESSION CLOSED';$('global').textContent=['SPX','NASDAQ','USDINR','CRUDE','GOLD'].map(k=>`${k} ${pct(m[k]?.change_pct)}`).join(' • ');$('newsCount').textContent=String((d.news||[]).length);
  const ev=d.evidence||[];$('evidence').innerHTML=ev.length?ev.map(x=>row(x,'OBSERVED','ok')).join(''):'<div class="muted">No independent evidence passed yet.</div>';
  $('closed').textContent=fmt(stats.closed||0);$('wins').textContent=`${stats.wins||0} / ${stats.losses||0}`;$('winRate').textContent=stats.win_rate!=null?pct(stats.win_rate):'—';$('realized').textContent=stats.realized_pct!=null?pct(stats.realized_pct):'—';$('drawdown').textContent=stats.max_drawdown_pct!=null?pct(stats.max_drawdown_pct):'—';$('lessons').textContent=Object.entries(j.lessons||{}).map(([k,v])=>`${k}:${v}`).join(' • ')||'No closed-trade lessons yet';
  const sourceRows=[['NIFTY price',n.fresh?'LIVE PUBLIC':'BLOCKED'],['India VIX',m.VIX?.fresh?'LIVE PUBLIC':'BLOCKED'],['Global markets',['SPX','NASDAQ','USDINR','CRUDE','GOLD'].filter(k=>m[k]?.fresh).length+'/5'],['Options',opt.status||'UNKNOWN'],['News',`${(d.news||[]).length} items`],['Validation',d.validation?.hit_rate!=null?'CALCULATED':'UNAVAILABLE'],['Overnight learning',learn.updated_at?new Date(learn.updated_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'WAITING'],['Time-of-day research',learn.pattern_stats?Object.keys(learn.pattern_stats).join(', '):'WAITING']];$('sources').innerHTML=sourceRows.map(x=>row(x[0],x[1],x[1].includes('BLOCK')||x[1].includes('UNKNOWN')?'warn':'ok')).join('');
  if(live.open){$('history').innerHTML=hist.slice(-20).reverse().map(x=>`<tr><td>${esc(x.ist_time?new Date(x.ist_time).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Kolkata'}):'—')}</td><td>${fmt(x.nifty)}</td><td class="${x.decision==='NO TRADE'?'warn':'ok'}">${esc(x.decision)}</td><td>${esc(x.contract||'—')}</td><td>${fmt(x.score)}</td><td>${esc(x.option_status||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No market-session decisions recorded yet.</td></tr>'}else $('history').innerHTML='<tr><td colspan="6">MARKET CLOSED — decision generation resumes at the next NSE session.</td></tr>';
  $('lastDecision').innerHTML=d.previous_decision?row('Previous closed trade',d.previous_decision.contract||'—')+row('Previous P/L',pct(d.previous_decision.realized_pct),d.previous_decision.realized_pct>=0?'ok':'bad')+row('Exit reason',d.previous_decision.exit_reason||'—'):row('Previous decision','No closed trade yet');
  $('refreshState').textContent='LIVE • '+new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
 }catch(e){$('refreshState').textContent='DATA ERROR';$('reason').textContent='The dashboard could not retrieve the latest cloud snapshot. No trade is issued.';}
}
load();setInterval(load,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});