const BUILD='10';const $=id=>document.getElementById(id);const fmt=x=>x==null||x===''?'—':typeof x==='number'?x.toLocaleString('en-IN',{maximumFractionDigits:2}):x;const pct=x=>x==null?'—':fmt(x)+'%';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const HOLIDAYS=new Set(['2026-01-26','2026-03-03','2026-03-26','2026-03-31','2026-04-03','2026-04-14','2026-05-01','2026-05-28','2026-06-26','2026-09-14','2026-10-02','2026-10-20','2026-11-10','2026-11-24','2026-12-25']);
function row(label,value,cls=''){return `<div class="row"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong></div>`}
function currentIST(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date());const o={};parts.forEach(p=>o[p.type]=p.value);return o}
function sessionState(){const p=currentIST(),key=`${p.year}-${p.month}-${p.day}`,mins=Number(p.hour)*60+Number(p.minute);const weekday=new Date(`${key}T00:00:00+05:30`).getUTCDay();return {open:weekday>=1&&weekday<=5&&!HOLIDAYS.has(key)&&mins>=555&&mins<=940,key,time:`${p.hour}:${p.minute}:${p.second}`}}
async function getJson(path){const r=await fetch(path+'?build='+BUILD+'&t='+Date.now(),{cache:'no-store',headers:{'Cache-Control':'no-cache','Pragma':'no-cache'}});if(!r.ok)throw Error(path+' '+r.status);return r.json()}
function mountChart(){if(document.getElementById('embeddedTraderChart'))return;const box=document.createElement('section');box.id='embeddedTraderChart';box.className='section panel';box.innerHTML='<h2>NIFTY 50 — 5-minute trader chart</h2><div style="height:620px;border:1px solid #203643;border-radius:12px;overflow:hidden;background:#071018"><iframe src="charts/realtime.html?v=10" title="NIFTY trader chart" style="width:100%;height:100%;border:0" loading="eager"></iframe></div><div class="notice">Candles and indicators come from the cloud 5-minute OHLC snapshot. The browser refreshes the chart automatically; it does not manufacture movement when the underlying public feed has not changed.</div>';const decision=document.querySelector('.decision');decision.parentNode.insertBefore(box,decision.nextSibling)}
async function load(){
 mountChart();$('refreshState').textContent='REFRESHING';
 try{
  const [d,h,j,learn]=await Promise.all([getJson('data/market_snapshot.json'),getJson('data/history.json').catch(()=>[]),getJson('data/trade_journal.json').catch(()=>({})),getJson('data/learning_state.json').catch(()=>({}))]);
  const live=sessionState();const m=d.market||{},n=m.NIFTY||{};const vixObj=m.VIX||{};const opt=d.option_data||{},cand=d.candidate||{},plan=d.plan||{},stats=j.stats||d.journal_stats||{},closed=j.closed||[];
  const nifty=d.nifty??n.price,vix=d.vix??vixObj.price,regime=d.regime||'RESEARCH MIXED',score=d.model_score??'RESEARCH';
  $('spot').textContent=fmt(nifty);$('vix').textContent=fmt(vix);$('regime').textContent=regime;$('score').textContent=fmt(score);$('marketTime').textContent=live.time;$('session').textContent=live.open?'MARKET OPEN':'MARKET CLOSED';
  const dec=live.open?(d.decision||'NO TRADE'):'MARKET CLOSED';$('decision').textContent=dec;$('decision').className=dec==='MARKET CLOSED'?'closed':dec==='NO TRADE'?'abstain':'trade';$('reason').textContent=live.open?(d.reason||'—'):'Trading decision is hidden outside NSE derivatives hours. Research, market data, evidence, learning and P/L remain visible.';$('strength').textContent=live.open?((d.signal_strength??0)+'/100'):'RESEARCH ACTIVE';$('optionGate').textContent=opt.status||'NOT VERIFIED';$('validation').textContent=d.validation?.hit_rate!=null?d.validation.hit_rate+'%':'RESEARCHING';$('openPnl').textContent=j.open?.unrealized_pct!=null?pct(j.open.unrealized_pct):'NO OPEN TRADE';$('lastPnl').textContent=closed.length?pct(closed[closed.length-1].realized_pct):'NO CLOSED TRADE';
  $('contract').textContent=live.open?(cand.contractSymbol||'NO VERIFIED CONTRACT'):'DECISION LOCKED UNTIL MARKET OPEN';$('entry').textContent=live.open&&plan.entry!=null?'₹'+fmt(plan.entry):'—';$('stop').textContent=live.open&&plan.stop!=null?'₹'+fmt(plan.stop):'—';$('targets').textContent=live.open&&plan.target1!=null?'₹'+fmt(plan.target1)+' / ₹'+fmt(plan.target2):'—';$('planNote').textContent=live.open?(plan.note||(opt.status==='BLOCKED_NO_RELIABLE_FREE_CHAIN'?'OPTION INTELLIGENCE: reliable free option-chain data is unavailable, so no contract is invented.':'No setup has passed every trade gate.')):'Only the final trading decision is locked outside market hours. Research data and previous trade results remain visible.';
  const daily=n.change_pct!=null?`1D ${pct(n.change_pct)} | Range ${fmt(n.low_5d)}–${fmt(n.high_5d)}`:'';$('trend').textContent=n.price?`${fmt(n.price)} | EMA20 ${n.ema20!=null?fmt(n.ema20):'research'} | EMA50 ${n.ema50!=null?fmt(n.ema50):'research'}${daily?' | '+daily:''}`:(nifty?'LAST AVAILABLE NIFTY '+fmt(nifty):'DATA SOURCE WAITING');$('rsi').textContent=n.rsi14!=null?fmt(n.rsi14):'NOT CALCULATED';$('vwap').textContent=`${n.vwap!=null?fmt(n.vwap):'NOT CALCULATED'} | ATR ${n.atr14!=null?fmt(n.atr14):'NOT CALCULATED'}`;$('momentum').textContent=`5m ${n.momentum5m_pct!=null?pct(n.momentum5m_pct):'SESSION CLOSED'} | 15m ${n.momentum15m_pct!=null?pct(n.momentum15m_pct):'SESSION CLOSED'}`;$('pcr').textContent=`PCR ${opt.pcr!=null?fmt(opt.pcr):'NOT VERIFIED'} | Max pain ${opt.max_pain!=null?fmt(opt.max_pain):'NOT VERIFIED'}`;$('optQuality').textContent=cand.candidate_score!=null?`${fmt(cand.candidate_score)}/100 | spread ${pct(cand.spread_pct)}`:(opt.status||'NOT VERIFIED — NO RELIABLE FREE CHAIN');$('global').textContent=['SPX','NASDAQ','USDINR','CRUDE','GOLD'].map(k=>`${k} ${m[k]?.change_pct!=null?pct(m[k].change_pct):'N/A'}`).join(' • ');$('newsCount').textContent=String((d.news||[]).length);
  const ev=d.evidence||[];$('evidence').innerHTML=ev.length?ev.map(x=>row(x,'OBSERVED','ok')).join(''):'<div class="muted">Research engine is waiting for the next cloud snapshot. No value is fabricated.</div>';
  $('closed').textContent=fmt(stats.closed||0);$('wins').textContent=`${stats.wins||0} / ${stats.losses||0}`;$('winRate').textContent=stats.win_rate!=null?pct(stats.win_rate):'—';$('realized').textContent=stats.realized_pct!=null?pct(stats.realized_pct):'—';$('drawdown').textContent=stats.max_drawdown_pct!=null?pct(stats.max_drawdown_pct):'—';$('lessons').textContent=Object.entries(j.lessons||{}).map(([k,v])=>`${k}:${v}`).join(' • ')||'No closed-trade lessons yet';
  const sourceRows=[['NIFTY price',n.fresh?'LIVE/LAST PUBLIC':nifty?'LAST AVAILABLE':'WAITING'],['India VIX',vixObj.fresh?'LIVE/LAST PUBLIC':vix?'LAST AVAILABLE':'WAITING'],['Global markets',['SPX','NASDAQ','USDINR','CRUDE','GOLD'].filter(k=>m[k]?.fresh).length+'/5'],['Options',opt.status||'NOT VERIFIED'],['News',`${(d.news||[]).length} items`],['Validation',d.validation?.hit_rate!=null?'CALCULATED':'RESEARCHING'],['Evidence engine',d.research_state?.evidence_engine||'ACTIVE'],['Cloud data timestamp',d.ist_time||'WAITING']];$('sources').innerHTML=sourceRows.map(x=>row(x[0],x[1],x[1].includes('WAIT')||x[1].includes('NOT VERIFIED')?'warn':'ok')).join('');
  $('history').innerHTML=Array.isArray(h)?h.slice(-20).reverse().map(x=>`<tr><td>${esc(x.ist_time?new Date(x.ist_time).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Kolkata'}):'—')}</td><td>${fmt(x.nifty)}</td><td class="${x.decision==='NO TRADE'?'warn':'ok'}">${esc(x.decision)}</td><td>${esc(x.contract||'—')}</td><td>${fmt(x.score)}</td><td>${esc(x.option_status||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No decision history yet.</td></tr>':'<tr><td colspan="6">History unavailable.</td></tr>';
  $('lastDecision').innerHTML=d.previous_decision?row('Previous closed trade',d.previous_decision.contract||'—')+row('Previous P/L',pct(d.previous_decision.realized_pct),d.previous_decision.realized_pct>=0?'ok':'bad')+row('Exit reason',d.previous_decision.exit_reason||'—'):row('Previous decision','No closed trade yet');
  $('refreshState').textContent='LIVE • '+live.time;
 }catch(e){$('refreshState').textContent='DATA ERROR';$('reason').textContent='Cloud data retrieval failed: '+e.message+'. No trade is issued.';console.error(e)}
}
load();setInterval(load,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});