"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, ChevronLeft, Building2, Target, Users, Globe2, BarChart3, MessageSquare, Sparkles } from "lucide-react";

type AssessmentField = [string, string, boolean];

type AssessmentStep = {
  title: string;
  icon: typeof Building2;
  fields: AssessmentField[];
};

const steps: AssessmentStep[] = [
  { title:"Business foundation", icon:Building2, fields:[["businessName","Business name",true],["industry","Industry / category",true],["city","Primary city / market",true],["serviceArea","Where do you serve customers?",true]] },
  { title:"Customers & offer", icon:Users, fields:[["idealCustomer","Who is your ideal customer?",true],["offerings","What are your main products or services?",true],["differentiator","Why do customers choose you?",true]] },
  { title:"Growth objective", icon:Target, fields:[["goal","Primary growth outcome",true],["target","What would success look like in 3–6 months?",true],["constraint","Biggest obstacle today",true]] },
  { title:"Current acquisition", icon:BarChart3, fields:[["channels","Where do customers currently come from?",true],["monthlyLeads","Approximate qualified enquiries per month",false],["conversion","Do you know your enquiry-to-customer rate?",false]] },
  { title:"Digital presence", icon:Globe2, fields:[["website","Website URL",false],["google","Google Business Profile URL",false],["instagram","Instagram / social profile URL",false],["otherLinks","Other important digital links",false]] },
  { title:"Your context", icon:MessageSquare, fields:[["challenge","What do you most want Vistaar to investigate?",true],["notes","Anything else we should know?",false]] }
];
const goals=["More qualified enquiries","More calls / WhatsApp conversations","More bookings / appointments","More store or location visits","More online sales","Improve digital presence","Build a stronger local market position","Increase repeat customers"];

export default function AssessmentPage(){
 const [step,setStep]=useState(0); const [form,setForm]=useState<Record<string,string>>({}); const [submitted,setSubmitted]=useState(false); const [sending,setSending]=useState(false); const [error,setError]=useState("");
 const current=steps[step]; const Icon=current.icon;
 const update=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const ready=current.fields.filter(x=>x[2]).every(x=>String(form[x[0]]||"").trim());
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setSending(true);try{const r=await fetch("/api/assessment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Unable to start assessment.");localStorage.setItem("vistaar_growth_assessment",JSON.stringify({id:d.id,businessId:d.businessId,auditId:d.auditId,form,createdAt:new Date().toISOString()}));localStorage.setItem("vistaar_biz_profile",JSON.stringify(d.profile));localStorage.setItem("vistaar_biz_audit",JSON.stringify({profile:d.profile,audit:d.audit,evidence:d.evidence||[],generatedAt:new Date().toISOString(),source:"detailed-assessment",businessId:d.businessId,auditId:d.auditId}));setSubmitted(true);window.setTimeout(()=>{window.location.href="/dashboard"},900)}catch(e){setError(e instanceof Error?e.message:"Unable to start assessment.")}finally{setSending(false)}};
 if(submitted)return <main className="assessmentPage"><div className="assessmentSuccess"><div className="assessmentMark"><Check size={25}/></div><span className="assessmentEyebrow">VISTAAR GROWTH ASSESSMENT · ANALYSED</span><h1>Your Vistaar workspace is <em>ready.</em></h1><p>We captured your business context, scanned the available website and local evidence, generated the first diagnosis and created your prioritised growth actions. Opening your workspace now.</p><div className="assessmentNext"><span><Sparkles size={15}/> BUSINESS CONTEXT</span><span><Globe2 size={15}/> DIGITAL SIGNALS</span><span><Target size={15}/> GROWTH OBJECTIVE</span></div><Link href="/dashboard" className="assessmentButton">Open your Vistaar workspace <ArrowRight size={16}/></Link><Link href="/" className="assessmentBack">Return to Vistaar-Biz</Link></div></main>;
 return <main className="assessmentPage"><div className="assessmentShell"><header className="assessmentHeader"><Link href="/" className="assessmentLogo"><span>V</span> VISTAAR<span className="logoDot">·</span>BIZ</Link><div><b>PROFESSIONAL ASSESSMENT</b><small>Separate from the 60-second readiness check.</small></div></header><div className="assessmentGrid"><aside><span className="assessmentEyebrow">VISTAAR GROWTH ASSESSMENT</span><h1>Let's understand the <em>whole business.</em></h1><p>This is the deeper assessment. We collect business context first, then combine it with relevant digital and market evidence to identify what deserves attention.</p><div className="assessmentPromise"><b>01 · BUSINESS</b><small>Goals, customers, offer and constraints</small><b>02 · EVIDENCE</b><small>Website, Google and relevant channels</small><b>03 · DIAGNOSIS</b><small>Evidence → priority → action</small></div><Link href="/#audit" className="assessmentBack">Looking for the quick readiness check? →</Link></aside><section className="assessmentCard"><div className="assessmentProgress"><span>STEP {String(step+1).padStart(2,"0")} / 06</span><div>{steps.map((_,i)=><i key={i} className={i<=step?"on":""}/>)}</div></div><div className="assessmentSectionTitle"><Icon size={19}/><div><span>ASSESSMENT INPUT</span><h2>{current.title}</h2></div></div><form onSubmit={submit}><div className="assessmentFields">{current.fields.map(([key,label,required])=><label key={key}><span>{label}{required&&<b>*</b>}</span>{key==="goal"?<select value={form[key]||""} onChange={e=>update(key,e.target.value)}><option value="">Select the primary outcome</option>{goals.map(g=><option key={g}>{g}</option>)}</select>:key==="offerings"||key==="idealCustomer"||key==="differentiator"||key==="target"||key==="constraint"||key==="channels"||key==="challenge"||key==="notes"||key==="otherLinks"?<textarea value={form[key]||""} onChange={e=>update(key,e.target.value)} rows={4} placeholder="Tell us in your own words..."/>:<input type={key==="website"||key==="google"||key==="instagram"?"url":"text"} value={form[key]||""} onChange={e=>update(key,e.target.value)} placeholder={key==="website"||key==="google"||key==="instagram"?"https://":"Type here..."}/>}</label>)}</div>{error&&<div className="assessmentError">{error}</div>}<div className="assessmentActions">{step>0?<button type="button" className="assessmentSecondary" onClick={()=>setStep(step-1)}><ChevronLeft size={16}/> Back</button>:<span className="assessmentHint">Focused on your business — not a generic checklist.</span>}{step<5?<button type="button" className="assessmentButton" disabled={!ready} onClick={()=>setStep(step+1)}>Continue <ArrowRight size={16}/></button>:<button type="submit" className="assessmentButton" disabled={!ready||sending}>{sending?"Starting assessment…":"Start Vistaar assessment"} <ArrowUpRight size={16}/></button>}</div></form></section></div></div></main>;
}
